admin_token: "changeme"
allowed_oauth_providers:
  - apple
  - google
  - guest
allowed_origins:
  - "http://localhost:8001"
  - "http://127.0.0.1:8001"
allowed_origin_regex: 'http://(localhost|127\.0\.0\.1)(:\d+)?'
