admin_token: "redukr"
allowed_oauth_providers:
  - apple
  - google
  - guest
allowed_origins:
  - "http://localhost:8001"
  - "http://127.0.0.1:8001"
  - "http://localhost:8002"
  - "http://127.0.0.1:8002"
allowed_origin_regex: "https?://(localhost|127\\.0\\.0\\.1)(:\\d+)?"
